# Generated by Django 4.0.4 on 2022-05-12 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestore', '0004_customuser_remove_library_games_remove_library_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(related_name='cart_customers', to='gamestore.game')),
                ('library', models.ManyToManyField(related_name='library_customers', to='gamestore.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(related_name='wishlist_customers', to='gamestore.game')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
