# Generated by Django 4.0.4 on 2022-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_customer_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_customers', to='gamestore.game'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='library_customers', to='gamestore.game'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_customers', to='gamestore.game'),
        ),
    ]
