# Generated by Django 4.0.4 on 2022-05-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0009_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
